import type { Metadata } from "next";
import { Cormorant_Upright, Figtree, IBM_Plex_Sans, Cinzel_Decorative, Outfit, Noto_Sans, Lora } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const cormorant = Cormorant_Upright({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-cormorant',
})

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-figtree',
})

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-ibm-plex-sans',
})

const cinzel = Cinzel_Decorative({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  variable: '--font-cinzel',
})

export const outfit = Outfit({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: '--font-outfit',
})

export const cloudyAurora = localFont({
  src: [
    {
      path: '../public/fonts/Cloudy Aurora Serif.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-cloudy',
})

export const notoSans = Noto_Sans({
  subsets: ['latin'],
  weight: ['300' ,'400', '500', '600', '700', '800'],
  variable: '--font-noto',
})

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-lora',
})

export const canelaTrial = localFont({
  src: [
    {
      path: '../public/fonts/Canela-Thin-Trial.otf',
      weight: '100',
      style: 'normal',
    }
  ],
  variable: '--font-canela',
})

export const theSignature = localFont({
  src: [
    {
      path: '../public/fonts/Thesignature.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-the-signature',
})

export const channe = localFont({
  src: [
    {
      path: '../public/fonts/Channe.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-channe',
})

export const perpetua = localFont({
  src: [
    {
      path: '../public/fonts/Perpetua Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-perpetua',
})

export const kunstler = localFont({
  src: [
    {
      path: '../public/fonts/kunstler.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-kunstler',
})

export const bellMt = localFont({
  src: [
    {
      path: '../public/fonts/Bell MT Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-bell-mt',
})

export const bickhamScript = localFont({
  src: [
    {
      path: '../public/fonts/Bickham Script Pro Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Bickham Script Pro Semibold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/Bickham Script Pro Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-bickham-script',
})

export const metadata: Metadata = {
  title: "Wedding Invitaion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`
        ${cormorant.variable} 
        ${figtree.variable} 
        ${ibmPlexSans.variable} 
        ${cinzel.variable} 
        ${outfit.variable} 
        ${cloudyAurora.variable} 
        ${notoSans.variable} 
        ${canelaTrial.variable} 
        ${theSignature.variable} 
        ${channe.variable} 
        ${perpetua.variable} 
        ${lora.variable} 
        ${kunstler.variable}
        ${bellMt.variable}
        ${bickhamScript.variable}`}
        >
        {children}
      </body>
    </html>
  );
}
