import type { Metadata } from "next";
import { Cormorant_Upright, Figtree, IBM_Plex_Sans, Cinzel_Decorative, Outfit, Noto_Sans } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const cormorant = Cormorant_Upright({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-cormorant',
})

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-figtree',
})

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-ibm-plex-sans',
})

const cinzel = Cinzel_Decorative({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  variable: '--font-cinzel',
})

export const outfit = Outfit({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-outfit',
})

export const cloudyAurora = localFont({
  src: [
    {
      path: '../public/fonts/Cloudy Aurora Serif.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-cloudy',
})

export const notoSans = Noto_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-noto',
})

export const canelaTrial = localFont({
  src: [
    {
      path: '../public/fonts/CanelaDeck-Regular-Trial.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-canela',
})

export const theSignature = localFont({
  src: [
    {
      path: '../public/fonts/Thesignature.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-the-signature',
})

export const metadata: Metadata = {
  title: "Wedding Invitaion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cormorant.variable} ${figtree.variable} ${ibmPlexSans.variable} ${cinzel.variable} ${outfit.variable} ${cloudyAurora.variable} ${notoSans.variable} ${canelaTrial.variable} ${theSignature.variable}`}>
        {children}
      </body>
    </html>
  );
}
